module.exports = {
	actionConst: {
		SET_USER_CURRENT_INPUT: 'SET_USER_CURRENT_INPUT',
		SUBMIT_USER_INPUT: 'SUBMIT_USER_INPUT',
		NEW_LOG_ENTRY: 'NEW_LOG_ENTRY',
		SEND_COMMAND: 'SEND_COMMAND',
		INVALID_COMMAND: 'INVALID_COMMAND',
		NEW_USER: 'NEW_USER',
		FOCUS_TAB: 'FOCUS_TAB',
		FOCUS_CARD: 'FOCUS_CARD',
		ASK_FOR_CARD: 'ASK_FOR_CARD',
	},
}
